[project]
name = "zenoti-excel-automation-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipykernel>=6.29.5",
    "ruff>=0.11.5",
]
